### ISSUE TITLE
Gathering requirements

### ISSUE THREAD

**Issue by ugurhicyilmam** [bogaziciswe/b.w.a.t#1]
Gather all project requirements regarding project. No format or limitation, add here whatever exists in your notes, or in your mind

**Comment by oakbas** [comment]
Should we also have a registration page for authenticated user? We should decide which data fields should be taken from the user. Then, this should be added to requirements document.

**Comment by oakbas** [comment]
We should also have short "how to get started" annotation page as shown in attached file.
<img width="1228" alt="howtopage" src="https://cloud.githubusercontent.com/assets/15357336/19027463/70836eca-8939-11e6-927b-012fcd9d89a2.png">

**Comment by ugurhicyilmam** [comment]
If by a registration page you mean an explicit web page, we won't have. The registration will be done on the plugin too.
