### ISSUE TITLE
Decide meeting note format

### ISSUE THREAD

**Issue by oakbas** [bogaziciswe/b.w.a.t#15]
Decide meeting note format, and add template document to here. 
After every meeting, notes should be added.

**Comment by oakbas** [comment]
Please review the format:
[meeting_minutes.docx](https://github.com/bogaziciswe/b.w.a.t/files/505753/meeting_minutes.docx)

**Comment by skynyrd** [comment]
I like the file format.

**Comment by ugurhicyilmam** [comment]
I like the format too. I remember mentioning a part about Decisions Made during the meeting. Perhaps it should be added too.

**Comment by ugurhicyilmam** [comment]
Following finalizing meeting format, can you please add it to the project wiki?
