### ISSUE TITLE
Prepare mockup diagrams for next show case.

### ISSUE THREAD

**Issue by skynyrd** [bogaziciswe/b.w.a.t#2]
UI mock up diagrams should be added to the project wiki page.
Not all the screens are necessary because of the fact that we did not extract all the features.
However, fundemental screens are required.

**Comment by gokhan-ozgozen** [comment]
What is mockup diagram ? You mean actual ui mocking right ? Not a diagram, but the mock itself ?

**Comment by sarahbe** [comment]
only UI mockup will be added, technical design diagrams will be added seperately to another issue.

**Comment by ugurhicyilmam** [comment]
I think we should create separate mock-up issues for each screen of the app instead of creating one global mock-up issue. That way we may have better documentation and progress track.

**Comment by sarahbe** [comment]
a separate issue will be created for each screen mockup. Issue is closed
