### ISSUE TITLE
Push message convention for Git

### ISSUE THREAD

**Issue by skynyrd** [bogaziciswe/b.w.a.t#4]
Hello everyone,

I think we should specify a convention for git messages in order to understand which commit is related to which issue.

I recommend using convention like this: "#IssueNumber explanation"

Example:
#003 initializes the project and sets up the mongo connection.
#016 adds selection functionality for the annotations.

What do you think about this convention?

Thanks.

**Comment by gokhan-ozgozen** [comment]
Sounds good to me.

**Comment by ugurhicyilmam** [comment]
I think it is good too.

**Comment by oakbas** [comment]
I also think it is ok, if everyone is agree on this, we can change state as resolve then close it.

**Comment by ozkuran** [comment]
I am also agreeing.
