### ISSUE TITLE
Add Example Annotation API

### ISSUE THREAD

**Issue by ugurhicyilmam** [bogaziciswe/b.w.a.t#47]
Add annotation api to the server.

Note that there are still lots of issues to make it specification clear about this.

Questions to be asked:

Is a secondary "annotation" database required?
Will there be a micro-service architecture?
Is MongoDB really required?

**Comment by ozkuran** [comment]
[Document](https://www.sitepoint.com/use-json-data-fields-mysql-databases/) related to JSON creation, reading, updating in MySQL usage.
