### ISSUE TITLE
Specifying the milestones

### ISSUE THREAD

**Issue by skynyrd** [bogaziciswe/b.w.a.t#5]
We need to specify what will be our short term goals and think about the proper date for each milestones.
Please comment what do you think about under this issue.

**Comment by oakbas** [comment]
How did we decide current milestones numbers? Is there any description about each milestone? Are they related with weeks or homework number specified in piazza?

**Comment by ozkuran** [comment]
I believe that first milestones would be related with requests made by professors in Piazza. So i have created 3 weekly milestones. 
As the length of the project taken into account, we may have biweekly milestones at most. A longer time between milestones may cause failure to measure the progress.
