### ISSUE TITLE
User Authentication Specification

### ISSUE THREAD

**Issue by gokhan-ozgozen** [bogaziciswe/b.w.a.t#9]
What user authentication method is sufficient ?
It is clear that users need to be authenticated, but Basic Auth. is enough ?
Needs more clarifications. [Requirements Document](https://github.com/bogaziciswe/b.w.a.t/blob/master/Requirements.md) will be updated accordingly.

**Comment by ugurhicyilmam** [comment]
I believe basic authentication is enough. Even though this program will not be running in production in near future, as long as the connection is SSL, there would not be any problem even in production.
